//
// Created by ruben on 04/06/19.
//

#ifndef MYINVINCIBLELIBRARY_METADATADB_DBCONTROLLER_H
#define MYINVINCIBLELIBRARY_METADATADB_DBCONTROLLER_H


class DBController {

};


#endif //MYINVINCIBLELIBRARY_METADATADB_DBCONTROLLER_H
